src/Entity/ReservationTransport.php
<?php

namespace App\Entity;

use App\Repository\ReservationTransportRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationTransportRepository::class)]
class ReservationTransport
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reservationTransports')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Transport $transport_id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_reservation = null;

    #[ORM\Column(length: 255)]
    private ?string $statut = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getTransportId(): ?Transport
    {
        return $this->transport_id;
    }

    public function setTransportId(Transport $transport_id): static
    {
        $this->transport_id = $transport_id;

        return $this;
    }

    public function getDateReservation(): ?\DateTimeInterface
    {
        return $this->date_reservation;
    }

    public function setDateReservation(\DateTimeInterface $date_reservation): static
    {
        $this->date_reservation = $date_reservation;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }
}

src/Form/ReservationTransportType.php
<?php

namespace App\Form;

use App\Entity\ReservationTransport;
use App\Entity\Transport;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationTransportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_reservation', null, [
                'widget' => 'single_text',
            ])
            ->add('statut')
            ->add('user_id', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
            ->add('transport_id', EntityType::class, [
                'class' => Transport::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ReservationTransport::class,
        ]);
    }
}

src/Controller/ReservationTransportController.php
<?php

namespace App\Controller;

use App\Entity\ReservationTransport;
use App\Form\ReservationTransportType;
use App\Repository\ReservationTransportRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/reservation/transport')]
final class ReservationTransportController extends AbstractController
{
    #[Route(name: 'app_reservation_transport_index', methods: ['GET'])]
    public function index(ReservationTransportRepository $reservationTransportRepository): Response
    {
        return $this->render('reservation_transport/index.html.twig', [
            'reservation_transports' => $reservationTransportRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reservation_transport_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservationTransport = new ReservationTransport();
        $form = $this->createForm(ReservationTransportType::class, $reservationTransport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservationTransport);
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_transport_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation_transport/new.html.twig', [
            'reservation_transport' => $reservationTransport,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_transport_show', methods: ['GET'])]
    public function show(ReservationTransport $reservationTransport): Response
    {
        return $this->render('reservation_transport/show.html.twig', [
            'reservation_transport' => $reservationTransport,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_transport_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ReservationTransport $reservationTransport, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationTransportType::class, $reservationTransport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_transport_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation_transport/edit.html.twig', [
            'reservation_transport' => $reservationTransport,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_transport_delete', methods: ['POST'])]
    public function delete(Request $request, ReservationTransport $reservationTransport, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservationTransport->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($reservationTransport);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reservation_transport_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation_transport/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_transport_delete', {'id': reservation_transport.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation_transport.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation_transport/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation_transport/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ReservationTransport{% endblock %}

{% block body %}
    <h1 class="mb-4">Edit ReservationTransport</h1>
<div class="mb-3">
    {{ include('reservation_transport/_form.html.twig', {'button_label': 'Update'}) }}
</div>
    <a href="{{ path('app_reservation_transport_index') }}" class="btn btn-secondary">back to list</a>

    {{ include('reservation_transport/_delete_form.html.twig') }}
{% endblock %}

templates/reservation_transport/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ReservationTransport index{% endblock %}

{% block body %}
    <h1 class="mb-4">ReservationTransport index</h1>
<div class="card p-4 shadow-lg rounded">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_reservation</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation_transport in reservation_transports %}
            <tr>
                <td>{{ reservation_transport.id }}</td>
                <td>{{ reservation_transport.dateReservation ? reservation_transport.dateReservation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservation_transport.statut }}</td>
                <td>
                    <a href="{{ path('app_reservation_transport_show', {'id': reservation_transport.id}) }}" class="btn btn-primary btn-sm">show</a>
                    <a href="{{ path('app_reservation_transport_edit', {'id': reservation_transport.id}) }}" class="btn btn-warning btn-sm">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" class="text-center">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
    <a href="{{ path('app_reservation_transport_new') }}" class="btn btn-success mt-2">Create new</a>
{% endblock %}

templates/reservation_transport/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ReservationTransport{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Create new ReservationTransport</h1>
<div class="mb-3">
    {{ include('reservation_transport/_form.html.twig') }}
</div>
    <a href="{{ path('app_reservation_transport_index') }}" class="btn btn-secondary">back to list</a>
</div>
{% endblock %}

templates/reservation_transport/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ReservationTransport{% endblock %}

{% block body %}
    <h1 class="mb-4">ReservationTransport</h1>
<div class="card p-4 shadow-lg rounded">

    <table class="table table-striped table-bordered">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation_transport.id }}</td>
            </tr>
            <tr>
                <th>Date_reservation</th>
                <td>{{ reservation_transport.dateReservation ? reservation_transport.dateReservation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ reservation_transport.statut }}</td>
            </tr>
        </tbody>
    </table>
</div>

    <a href="{{ path('app_reservation_transport_index') }}" class="btn btn-secondary">back to list</a>

    <a href="{{ path('app_reservation_transport_edit', {'id': reservation_transport.id}) }}" class="btn btn-warning">edit</a>

    {{ include('reservation_transport/_delete_form.html.twig') }}
{% endblock %}